version: "3.8"
services:
  python-app:
    image: python-app
    container_name: raffle-bot-container
    environment:
      - CONFIG_FILE_PATH=/config.json
    volumes:
      - ${CONFIG_FILE_PATH}:/config.json

